# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Hugo Klise"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "The theme for hugo based on the existing klisé theme for jekyll"
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "me"
  homepage = "home"

# If porting an existing theme
[original]
  name = "jekyll-klise"
  homepage = "klise.vercel.app/"
  repo = "https://github.com/piharpi/jekyll-klise"
