baseURL = "https://h4r1337.github.io/hugo-klise/"
title = "Hugo Themes"
author = "h4r1337"
copyright = "Copyright © 2022; all rights reserved."
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# set your theme to "hugo-klise"
theme = "../.."
publishDir = "../docs"

[permalinks]
'/' = '/hugo-klise/'

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/posts/"
    weight = 2
    pre = ""
    post = ""
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 3
    pre = ""
    post = ""
  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1
    # you can add extra information before the name (HTML format is supported), such as icons
    # fontawesome icons are supported 
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    # fontawesome icons are supported 
    post = ""

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[params]
  # default mode ("light", "dark")
  mode = "dark"

  # type of sections to add in the recent posts section
  mainSections = ["blog", "docs", "posts", "post", "homepage"]

  # show summary section of each page
  # options: "none", "description", "summary"
  # "description" shows content from the the .Description of frontmatter
  # "summary" shows .Summary of the page
  showSummary = "none"
  
  [params.author]
  name = "Hugo Klisé"
  bio = "The minimalist Hugo theme, light and dark mode support, for running a personal site and blog, meet Klisé theme at <a href='https://github.com/h4r1337/hugo-klise' target='_blank' rel='noopener;'>@github</a>"
  username = "username"
  github = "github_username"
  twitter = "twitter_username"
  facebook = "facebook_username"
  email = "your-email@email.com"
  avatar = "/img/avatar.jpg"

  [params.section]
    paginate = 20

[markup]
  [markup.highlight]
    # Add this option if you want to use the custom gruvbox theme
    # for code highlighting. If you don't use this option
    # the code highlight theme will be the defaut monokai theme from hugo.
    noClasses = false

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
